module.exports = {
  'application/vnd.google-apps.audio': 'application/zip',
  'application/vnd.google-apps.document': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.google-apps.drawing': 'image/png',
  'application/vnd.google-apps.file': 'application/zip',
  'application/vnd.google-apps.folder': 'application/zip',
  'application/vnd.google-apps.form': 'application/zip',
  'application/vnd.google-apps.fusiontable': 'application/zip',
  'application/vnd.google-apps.map': 'application/zip',
  'application/vnd.google-apps.photo': 'application/zip',
  'application/vnd.google-apps.presentation': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.google-apps.script': 'application/zip',
  'application/vnd.google-apps.site': 'application/zip',
  'application/vnd.google-apps.spreadsheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.google-apps.unknown': 'application/zip',
  'application/vnd.google-apps.video': 'application/zip',
  'application/vnd.google-apps.drive-sdk': 'application/zip',
};
